version: 2

sources:
  - name: tap_s3_csv
    schema: tap_s3_csv
    tables:
      - name: customers
      - name: orders
      - name: products
      - name: order_details

models:
  - name: customers
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders

    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null

      - name: address
        description: Customer's first name. PII.

      - name: city
        description: Customer's last name. PII.

      - name: company_name
        description: Date (UTC) of a customer's first order

      - name: contact_name
        description: Date (UTC) of a customer's most recent order

      - name: contact_title
        description: Count of the number of orders a customer has placed

      - name: country
        description: Total value (AUD) of a customer's orders

  - name: orders
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders

    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null

      - name: employee_id
        description: This column represents the identifier of the employee associated with the order

      - name: freight
        description: This column denotes the freight or shipping cost associated with the order

      - name: order_date
        description: This column indicates the date when the order was placed by the customer

      - name: order_id
        description: This column serves as a unique identifier for each order

      - name: required_date
        description: This column signifies the date by which the customer expects to receive the ordered products

      - name: ship_address
        description: This column contains the shipping address where the ordered products are to be delivered

      - name: ship_city
        description: This column specifies the city to which the ordered products are to be shipped

      - name: ship_country
        description: This column denotes the country to which the ordered products are to be shipped

      - name: ship_name
        description: This column represents the name associated with the shipping address

      - name: ship_postal_code
        description: This column contains the postal or ZIP code of the shipping address

      - name: ship_region
        description: This column denotes the region or state/province to which the ordered products are to be shipped

      - name: ship_via
        description:  This column represents the shipping method or carrier used to deliver the products to the customer

      - name: shipped_date
        description: This column indicates the date when the ordered products were shipped or dispatched from the warehouse

  - name: products
    description: This table contains information about products available for sale

    columns:
      - name: product_id
        description: Unique identifier for each product

      - name: product_name
        description: Name of the product

      - name: category_id
        description: Identifier for the category to which the product belongs

      - name: supplier_id
        description: Identifier for the supplier of the product

      - name: quantity_per_unit
        description: Quantity per unit of the product

      - name: unit_price
        description: Price per unit of the product

      - name: units_in_stock
        description: Number of units currently in stock

      - name: units_on_order
        description: Number of units currently on order

      - name: reorder_level
        description: Level at which the product needs to be reordered

      - name: discontinued
        description: Flag indicating if the product has been discontinued

  - name: order_details
    description: This table contains detailed information about the products included in each order

    columns:
      - name: order_id
        description: Identifier for the order

      - name: product_id
        description: Identifier for the product included in the order

      - name: unit_price
        description: Price per unit of the product at the time of the order

      - name: quantity
        description: Quantity of the product included in the order

      - name: discount
        description: Discount applied to the product in the order